// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3CubyzPGt0KRm55JpSbdzM5nny4IBZMA',
    appId: '1:510914087054:android:d7fb0e6c382fef5085a1df',
    messagingSenderId: '510914087054',
    projectId: 'dr-meshal',
    storageBucket: 'dr-meshal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVHO-o-suZ1-w1cvG1CdmH1oM6hlm0Xk',
    appId: '1:510914087054:ios:2b8dfbb2d989433d85a1df',
    messagingSenderId: '510914087054',
    projectId: 'dr-meshal',
    storageBucket: 'dr-meshal.firebasestorage.app',
    androidClientId: '510914087054-udbdeaoqcv1qbugn1e2cvdq7uo3ki4kc.apps.googleusercontent.com',
    iosClientId: '510914087054-gsksdrol92ri300vpfad3ttn34hj3fnt.apps.googleusercontent.com',
    iosBundleId: 'com.safatech.doctormeshalapp',
  );
}
